export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const FORGOT_PASSWORD_BEGIN = 'FORGOT_PASSWORD_BEGIN'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR'

export const RESET_PASSWORD_BEGIN = 'RESET_PASSWORD_BEGIN'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const TOGGLE_ADMIN_SIDEBAR = 'TOGGLE_ADMIN_SIDEBAR'

export const HANDLE_CHANGE_PRODUCT_GLOBAL = 'HANDLE_CHANGE_PRODUCT_GLOBAL'

export const CREATE_PRODUCT_BEGIN = 'CREATE_PRODUCT_BEGIN'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_ERROR = 'CREATE_PRODUCT_ERROR'

export const FETCH_PRODUCT_BEGIN = 'FETCH_PRODUCT_BEGIN'
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS'
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR'

export const SET_PRODUCT_ID = 'SET_PRODUCT_ID'

export const SHOW_EDIT_MODAL = 'SHOW_EDIT_MODAL'
export const SHOW_DELETE_MODAL = 'SHOW_DELETE_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'

export const UPDATE_PRODUCT_BEGIN = 'UPDATE_PRODUCT_BEGIN'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'
export const RE_FETCH_NEW_UPDATED_PRODUCTS = 'RE_FETCH_NEW_UPDATED_PRODUCTS'

export const DELETE_PRODUCT_BEGIN = 'DELETE_PRODUCT_BEGIN'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const SHOW_STATS_BEGIN = 'SHOW_STATS_BEGIN'
export const SHOW_STATS_SUCCESS = 'SHOW_STATS_SUCCESS'

export const GET_SEARCH_PRODUCT_INPUT = 'GET_SEARCH_PRODUCT_INPUT'
export const CHANGE_PAGE = 'CHANGE_PAGE'

export const FETCH_SINGLE_PRODUCT_DETAIL_BEGIN =
  'FETCH_SINGLE_PRODUCT_DETAIL_BEGIN'
export const FETCH_SINGLE_PRODUCT_DETAIL_SUCCESS =
  'FETCH_SINGLE_PRODUCT_DETAIL_SUCCESS'
export const FETCH_SINGLE_PRODUCT_DETAIL_ERROR =
  'FETCH_SINGLE_PRODUCT_DETAIL_ERROR'

export const ADD_INFO_OF_PRODUCTS_TO_CART = 'ADD_INFO_OF_PRODUCTS_TO_CART'
export const GET_TOTAL_PRICE_OF_PRODUCTS_IN_CART =
  'GET_TOTAL_PRICE_OF_PRODUCTS_IN_CART'
export const ADD_INFO_OF_PRODUCTS_TO_CART_WITHOUT_GOING_INTO_ITS_DETAIL_PAGE =
  'ADD_INFO_OF_PRODUCTS_TO_CART_WITHOUT_GOING_INTO_ITS_DETAIL_PAGE'
